### ISSUE TITLE
login: failed to check token: missing apikey

### ISSUE THREAD

**Issue by zhfish** [apache/apisix-dashboard#2032]
## Issue description
```
version: "2"

services:
  apisix-dashboard:
    image: apache/apisix-dashboard:2.7
    restart: always
    volumes:
    - /opt/apisix/dashboard.yaml:/usr/local/apisix-dashboard/conf/conf.yaml
    ports:
    - "9000:80"
    depends_on:
      - apisix

  apisix:
    image: apache/apisix:2.8-alpine
    restart: always
    volumes:
      - /data/apisix/log:/usr/local/apisix/logs
      - /opt/apisix/apisix.yaml:/usr/local/apisix/conf/config.yaml:ro
    depends_on:
      - etcd
    #network_mode: host
    ports:
      - "80:80/tcp"
      - "443:443/tcp"

  etcd:
    image: bitnami/etcd:3.5.0
    user: root
    restart: always
    volumes:
      - /data/apisix/etcd:/bitnami/etcd
    environment:
      ETCD_ENABLE_V2: "true"
      ALLOW_NONE_AUTHENTICATION: "yes"
      ETCD_ADVERTISE_CLIENT_URLS: "http://0.0.0.0:2379"
      ETCD_LISTEN_CLIENT_URLS: "http://0.0.0.0:2379"
```
http://127.0.0.1:9000 login is ok
http://gw.my.comlogin is 401
```
2021/08/04 03:29:28 [warn] 46#46: *181149 [lua] init.lua:125: handler(): failed to check token: missing apikey, client: 1.2.3.232, server: _, request: "POST /apisix/admin/user/login HTTP/1.1", host: "gw.my.com"
```

## Environment

* apisix version (cmd: `apisix version`): 2.8
* apisix-dashboard version, if have: 2.7

## Additional context
#590 
#464
