### ISSUE TITLE
How to configure DNS Discovery with Dashboard?

### ISSUE THREAD

**Issue by lazychanger** [apache/apisix-dashboard#2424]
## 基本情况
- namespace: ingress-apisix
  - apisix
  - apisix-ingress-controlls
  - apisix-admin
  - apisix-dashboard
- namespace: default
  - nginx

## 操作流程
1. 创建上游
<img width="1405" alt="image" src="https://user-images.githubusercontent.com/20916944/162917364-985ce050-972c-464b-a0df-53e567d84db4.png">
2. 创建路由 <br/>
3. 访问路由 <br/>
4. 503 Service Temporarily Unavailable
<img width="1445" alt="image" src="https://user-images.githubusercontent.com/20916944/162918208-22468f9f-dc09-48c3-90e7-1df2b966f2d9.png">

## 涉及到apisix-ingress代码
https://github.com/apache/apisix-ingress-controller/blob/b7dd90ad9d6a5102fe67c91c29ab76fc4bad4b1a/pkg/kube/translation/util.go#L38

## 通过kubectl create设置命名空间就可以访问
```yaml
---
apiVersion: apisix.apache.org/v2beta3
kind: ApisixRoute
metadata:
  name: nginx
  namespace: default
spec:
  http:
    - name: nginx
      match:
        hosts:
          - test.xxxx.com
        paths:
          - "/*"
      backends:
        - serviceName: nginx-headless
          servicePort: 80
```

<img width="1378" alt="image" src="https://user-images.githubusercontent.com/20916944/162918478-faa9d32f-f7e6-4734-9a15-17e603657368.png">

### Expected behavior

service "nginx-headless.default.svc.cluster.local" not found

### How to Reproduce

如问题描述

## ENV
<img width="967" alt="image" src="https://user-images.githubusercontent.com/20916944/162918714-92c4a11a-872e-44d2-821f-0fc24d28bc70.png">

## install shell
```yaml
helm repo add apisix https://charts.apiseven.com

helm repo add bitnami https://charts.bitnami.com/bitnami

helm repo update

helm install apisix apisix/apisix \
  --set gateway.type=LoadBalancer \
  --set ingress-controller.enabled=true \
  --set etcd.persistence.storageClass="apisix" \
  --set etcd.persistence.size="20Gi" \
  --namespace ingress-apisix \
  --set gateway.tls.enabled=true \
  --set ingress-controller.config.apisix.adminKey="******" \
  --set admin.credentials.admin="******" \
  --set admin.credentials.viewer="******" \
  --set ingress-controller.config.apisix.serviceNamespace=ingress-apisix \
  --set dashboard.enabled=true \
  --set dashboard.config.authentication.users[0].username=**** \
  --set dashboard.config.authentication.users[0].password="*******"
```
