### ISSUE TITLE
Dashboard of APISIX-dashboard seem to work incorrectly.

### ISSUE THREAD

**Issue by Chever-John** [apache/apisix-dashboard#2546]
### Issue description

Yes, I know this may be an issue since the introduction of Content-security-policy. But I'm still not getting the results I want when I follow this line of thinking to configure it. So I came to ask for your help.

I noticed that this issue has come up before, but there has been no solution left. This issues will completely solve the problem!

<img width="1478" alt="image" src="https://user-images.githubusercontent.com/43690894/181296445-74a01cfa-a432-441c-a5b3-b2e5123fdae2.png">

### Expected behavior

The dashboard display is normal.

### How to Reproduce

First, we will use the "APISIX-docker" repo.

your env
<img width="991" alt="image" src="https://user-images.githubusercontent.com/43690894/181295721-eec9a514-0154-44ac-b13f-f4fbfe8cda53.png">

1. git clone `apisix-docker`;
2. `cd apisix-docker/example`;
4. run the command `vim dashboard_conf/conf.yaml`;
5. add the following configuration:
```yaml
security:
  access_control_allow_origin: "http://httpbin.org"
  access_control_allow_credentials: true          # support using custom cors configration
  access_control_allow_headers: "Authorization"
  access_control-allow_methods: "*"
  x_frame_options: "deny"
  content_security_policy: "default-src 'self'; script-src 'self' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; frame-src http://127.0.0.1:3000"
```
6. run the command `docker-compose -p docker-apisix -f docker-compose.yml up -d`;
7. Then you will see the result as follows:
<img width="960" alt="image" src="https://user-images.githubusercontent.com/43690894/181296956-28eebe40-164c-45cc-aa16-a9150e6d8d89.png">

### Screenshots

<img width="961" alt="image" src="https://user-images.githubusercontent.com/43690894/181297808-92492565-2ebb-4990-b413-96678be1fa08.png">

### Environment

- apisix version (cmd: `apisix version`): 2.14.1-alpine
- OS (cmd: `uname -a`): Linux vultr 5.4.0-122-generic #138-Ubuntu SMP Wed Jun 22 15:00:31 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`): nginx/1.18.0 (Ubuntu) /  openresty/1.21.4.1
- etcd version, if have (cmd: run `etcd --version`): 3.4.15
- apisix-dashboard version, if have: 2.13-alpine
- Browser version, if have: Version 103.0.5060.134 (Official Build) (arm64)
