### ISSUE TITLE
切换2.13.1后连接etcd报错

### ISSUE THREAD

**Issue by coolmingwu** [apache/apisix-dashboard#2681]
### Issue description

切换dashboard版本后，日志报错
![image](https://user-images.githubusercontent.com/93962343/205550006-12f5f193-653e-4117-97e5-fc20c5cc2119.png)

### Expected behavior

切换版本后不影响使用

### How to Reproduce

直接切换dashboard版本

### Environment

- apisix version (cmd: `apisix version`):
- OS (cmd: `uname -a`):
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `etcd --version`):
- apisix-dashboard version, if have:
- Browser version, if have:

**Comment by nhlzh8708** [comment]
这个问题看像是etcd的ETCD_ADVERTISE_CLIENT_URLS参数，配置成了http://0.0.0.0:2379，把这个配置改成客户端能访问的IP就行，我也遇到过。
```
 etcd:
    container_name: etcd
    image: *****/bitnami/etcd:3.4.13-debian-10-r7
    user: root
    restart: always
    environment:
      ETCD_ENABLE_V2: "true"
      ALLOW_NONE_AUTHENTICATION: "yes"
      ETCD_ADVERTISE_CLIENT_URLS: "http://etcd:2379"
      ETCD_LISTEN_CLIENT_URLS: "http://0.0.0.0:2379"
```
