### ISSUE TITLE
升级后报etcd connection loss detected和transport: Error while dialing dial tcp 0.0.0.0:2381: connect: connection refused 错误

### ISSUE THREAD

**Issue by yinyuncan** [apache/apisix-dashboard#2733]
### Issue description

控制台重复输出报错日志
` {"level":"warn","ts":"2023-02-08T07:57:13.333Z","logger":"etcd-client","caller":"v3@v3.5.5/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc0001841c0/10.0.0.80:2381","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = latest balancer error: last connection error: connection error: desc = \"transport: Error while dialing dial tcp 0.0.0.0:2381: connect: connection refused\""}`

日志文件error.log报错：
`ERROR	cmd/root.go:107	etcd connection loss detected, times: 19
WARN	store/store.go:128	data not found by key: 388640600313824312`

### Expected behavior

应该可以正常更新路由

### How to Reproduce

0. 从2.10.1版本升级到2.15.1 才发现路由更新不了这个错误，一看日志就有报错
1. 随便新增一个路由，更新报错，截图如下
2. 启动后控制台重复输出报错日志

### Screenshots

![Uploading image.png…]()

### Environment

etcd版本3.4.15
etcd是否为集群：否
网络环境是否畅通：是
apisix-dashboard版本：2.15.0-centos
apisix版本：2.15.1-centos
Docker version 20.10.12,

### Additional context

这个是配置文件
```yaml
conf:
    listen:
        host: 0.0.0.0     # `manager api` listening ip or host name
        port: 9000          # `manager api` listening port
    allow_list: # If we don't set any IP list, then any IP access is allowed by default.
        - 0.0.0.0/0
    etcd:
        endpoints: # supports defining multiple etcd host addresses for an etcd cluster
            - "http://10.0.0.80:2381"
         
            key_file: ""          # Path of your self-signed client side key
            cert_file: ""         # Path of your self-signed client side cert
            ca_file: ""           # Path of your self-signed ca cert, the CA is used to sign callers' certificates

    log:
        error_log:
            level: warn       # supports levels, lower to higher: debug, info, warn, error, panic, fatal
            file_path:
                logs/error.log  # supports relative path, absolute path, standard output
            # such as: logs/error.log, /tmp/logs/error.log, /dev/stdout, /dev/stderr
        access_log:
            file_path:
                logs/access.log  # supports relative path, absolute path, standard output
              # such as: logs/access.log, /tmp/logs/access.log, /dev/stdout, /dev/stderr
            # log example: 2020-12-09T16:38:09.039+0800	INFO	filter/logging.go:46	/apisix/admin/routes/r1	{"status": 401, "host": "127.0.0.1:9000", "query": "asdfsafd=adf&a=a", "requestId": "3d50ecb8-758c-46d1-af5b-cd9d1c820156", "latency": 0, "remoteIP": "127.0.0.1", "method": "PUT", "errs": []}
authentication:
    secret:
        secret              # secret for jwt token generation.
      # NOTE: Highly recommended to modify this value to protect `manager api`.
    # if it's default value, when `manager api` start, it will generate a random string to replace it.
    expire_time: 36000     # jwt token expire time, in second
    users: # yamllint enable rule:comments-indentation
        -   username: xxx   # username and password for login `manager api`
            password: xxx@

plugins: # plugin list (sorted in alphabetical order)
    - api-breaker
    - authz-casbin
    - authz-casdoor
    - authz-keycloak
    - aws-lambda
    - azure-functions
    - basic-auth
    # - batch-requests
    - clickhouse-logger
    - client-control
    - consumer-restriction
    - cors
    - csrf
    - datadog
    # - dubbo-proxy
    - echo
    - error-log-logger
    # - example-plugin
    - ext-plugin-post-req
    - ext-plugin-post-resp
    - ext-plugin-pre-req
    - fault-injection
    - file-logger
    - forward-auth
    - google-cloud-logging
    - grpc-transcode
    - grpc-web
    - gzip
    - hmac-auth
    - http-logger
    - ip-restriction
    - jwt-auth
    - kafka-logger
    - kafka-proxy
    - key-auth
    - ldap-auth
    - limit-conn
    - limit-count
    - limit-req
    - loggly
    # - log-rotate
    - mocking
    # - node-status
    - opa
    - openid-connect
    - opentelemetry
    - openwhisk
    - prometheus
    - proxy-cache
    - proxy-control
    - proxy-mirror
    - proxy-rewrite
    - public-api
    - real-ip
    - redirect
    - referer-restriction
    - request-id
    - request-validation
    - response-rewrite
    - rocketmq-logger
    - server-info
    - serverless-post-function
    - serverless-pre-function
    - skywalking
    - skywalking-logger
    - sls-logger
    - splunk-hec-logging
    - syslog
    - tcp-logger
    - traffic-split
    - ua-restriction
    - udp-logger
    - uri-blocker
    - wolf-rbac
    - zipkin
```

**Comment by Baoyuantop** [comment]
How did you deploy apisix and dashboard?

**Comment by lemonrains** [comment]
Same problem. if i config etcd -> endpoints with custom config

**Comment by yinyuncan** [comment]
> How did you deploy apisix and dashboard?

This is the docker-compose deployment file
docker-compose.yml
```yml
version: "3"
services:
  apisix-dashboard:
    image: apache/apisix-dashboard:2.15.0-centos
    container_name: apisix-dashboard
    restart: always
    volumes:
    - ./dashboard_conf/conf.yaml:/usr/local/apisix-dashboard/conf/conf.yaml
    - ./dashboard_log:/usr/local/apisix-dashboard/logs
    ports:
    - "9000:9000"
    networks:
      apisix:
  apisix:
    image: apache/apisix:2.15.1-centos
    container_name: apisix
    restart: always
    volumes:
      - ./apisix_log:/usr/local/apisix/logs
      - ./apisix_conf/config.yaml:/usr/local/apisix/conf/config.yaml
    depends_on:
      - etcd
    ##network_mode: host
    ports:
      # http
      - "80:80/tcp"
      # https
      - "443:443/tcp"
      # apisix管理端接口
      - "9080:9080"
      # 内部状态信息
      - "9099:9099"
      # prometheus指标
      - "9091:9091"
      # mqtt/tcp
      - "1999:1999/tcp"
      # 数据库/tcp
      - "2021:1998/tcp"
    networks:
      apisix:

  etcd:
    image: bitnami/etcd:3.4.15
    container_name: etcd
    restart: always
    privileged: true
    volumes:
      - etcd_data:/bitnami/etcd
    environment:
      ETCD_ENABLE_V2: "true"
      ALLOW_NONE_AUTHENTICATION: "yes"
      ETCD_ADVERTISE_CLIENT_URLS: "http://0.0.0.0:2381"
      ETCD_LISTEN_CLIENT_URLS: "http://0.0.0.0:2381"
    ports:
      - "2381:2381/tcp"
    networks:
      apisix:
networks:
  apisix:
    driver: bridge

volumes:
  etcd_data:
    driver: local

```
