### ISSUE TITLE
apisix-dashboard v3.0.1 send put  delete request can not success

### ISSUE THREAD

**Issue by danielmlc** [apache/apisix-dashboard#2896]
### Issue description

In the apisix-dashboard, all page data queries are successful, but all write operations time out. The deployment is done using Docker. The apisix version is 3.7, and the dashboard version is 3.0.1
![微信截图_20231201191043](https://github.com/apache/apisix-dashboard/assets/16604995/3497ff75-e178-465a-9464-b7f71dbb7e74)

### Expected behavior

In the apisix-dashboard, all page data queries are successful, but all write operations time out. The deployment is done using Docker. The apisix version is 3.7, and the dashboard version is 3.0.1

### How to Reproduce

this is yaml config:

apisix
```yaml

apisix:
  node_listen: 9080              # APISIX listening port
  enable_ipv6: false

  enable_control: true
  control:
    ip: "0.0.0.0"
    port: 9092

deployment:
  admin:
    allow_admin:               # https://nginx.org/en/docs/http/ngx_http_access_module.html#allow
      - 0.0.0.0/0              # We need to restrict ip access rules for security. 0.0.0.0/0 is for test.

    admin_key:
      - name: "admin"
        key: edd1c9f034335f136f87ad84b625c8f1
        role: admin                 # admin: manage all configuration data

      - name: "viewer"
        key: 4054f7cf07e344346cd3f287985e76a2
        role: viewer

  etcd:
    host:                           # it's possible to define multiple etcd hosts addresses of the same etcd cluster.
      - "http://etcd:2379"          # multiple etcd address
    prefix: "/apisix"               # apisix configurations prefix
    timeout: 30                     # 30 seconds

plugin_attr:
  prometheus:
    export_addr:
      ip: "0.0.0.0"
      port: 9091

```
dashboard

```yaml

apisix:
  node_listen: 9080              # APISIX listening port
  enable_ipv6: false

  enable_control: true
  control:
    ip: "0.0.0.0"
    port: 9092

deployment:
  admin:
    allow_admin:               # https://nginx.org/en/docs/http/ngx_http_access_module.html#allow
      - 0.0.0.0/0              # We need to restrict ip access rules for security. 0.0.0.0/0 is for test.

    admin_key:
      - name: "admin"
        key: edd1c9f034335f136f87ad84b625c8f1
        role: admin                 # admin: manage all configuration data

      - name: "viewer"
        key: 4054f7cf07e344346cd3f287985e76a2
        role: viewer

  etcd:
    host:                           # it's possible to define multiple etcd hosts addresses of the same etcd cluster.
      - "http://etcd:2379"          # multiple etcd address
    prefix: "/apisix"               # apisix configurations prefix
    timeout: 30                     # 30 seconds

plugin_attr:
  prometheus:
    export_addr:
      ip: "0.0.0.0"
      port: 9091

```

### Environment

- apisix version (cmd: `apisix version`):3.7
- OS (cmd: `uname -a`):ubantu22.04
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `etcd --version`):3..4.01
- apisix-dashboard version, if have:3.0.1
- Browser version, if have:
