### ISSUE TITLE
Absolute file path reference causes path base ingress fail #ingress #rewrite-target-regex #ImplementationSpecific

### ISSUE THREAD

**Issue by damoshushu** [apache/apisix-dashboard#2921]
### Issue description

Hi Apisix Team,

I am trying to config the ingress of dashboard service as following, however I found that accessing the dashboard page failed with an error. It is because the files referenced in the main page are using absolute path.

```
dashboard:
  enabled: true
  ingress:
    enabled: true
    className: apisix
    annotations:
      k8s.apisix.apache.org/rewrite-target-regex: "/dashboard/(.*)"
      k8s.apisix.apache.org/rewrite-target-regex-template: "/$1"
    hosts:
    - host: apisix-dashboard.local
      paths: &dashboard_paths
        - "/dashboard"
        - "/dashboard/*"
    - host: www.xxx.io
      paths: *dashboard_paths
```

![image](https://github.com/apache/apisix-dashboard/assets/24828250/66d36131-150e-4f3e-8225-01e420318a2b)

### Expected behavior

relative path is expected to be used, and it should support path based ingress rule

### How to Reproduce

deploy the ingress with a specified path rather than "/"

### Environment

- apisix version (cmd: `apisix version`):
- OS (cmd: `uname -a`):
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `etcd --version`):
- apisix-dashboard version, if have:
- Browser version, if have:
