### ISSUE TITLE
docker-componse方式无法连接到etcd

### ISSUE THREAD

**Issue by longjie12315** [apache/apisix-dashboard#2972]
### Issue description

docker-compose.yml
```
version: "3.1"
services:
  etcd:
    hostname: etcd
    image: bitnami/etcd:3.4.35
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://127.0.0.1:2379
    ports:
      - 2379:2379
      - 2380:2380
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - egmp
  apisix:
    hostname: apisix
    image: apache/apisix:3.11.0-debian
    ports:
      - 9180:9180
      - 9080:9080
    volumes:
      - ./apisix/conf/config.yaml:/usr/local/apisix/conf/config.yaml
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - egmp
  apisix-dashboard:
    hostname: apisix-dashboard
    image: apache/apisix-dashboard:3.0.1-centos
    ports:
      - 19000:9000
    volumes:
      - ./apisix-dashboard/conf/conf.yaml:/usr/local/apisix-dashboard/conf/conf.yaml
      - ./apisix-dashboard/logs:/usr/local/apisix-dashboard/logs
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - egmp
      
networks:
  egmp:
```
conf.yaml
```
conf:
  listen:
    port: 9000
  etcd:
    endpoints:
      - "http://etcd:2379"
```

![image](https://github.com/user-attachments/assets/1e8f7571-a8d0-461f-a383-1cd7d39d1b46)

![image](https://github.com/user-attachments/assets/2291f1c4-4e81-4a67-87b9-88e75f06ee73)

### Expected behavior

我需要如何配置能正确运行

### How to Reproduce

使用docker命令
docker stack deploy -c docker-compose.yml  egmp
