### ISSUE TITLE
OIDC Authentication with Keycloak Not Working

### ISSUE THREAD

**Issue by bo-unitysvc** [apache/apisix-dashboard#3003]
## Problem Description
I'm trying to enable OIDC authentication in APISIX Dashboard using Keycloak, but I'm still seeing the regular login page instead of being redirected to Keycloak. When manually navigating to `/apisix/admin/oidc/login`, I get an error: `Invalid parameter: redirect_uri`.

## Configuration
I've updated my`/usr/local/apisix-dashboard/conf/conf.yaml` with:

```yaml
oidc:
  enabled: true
  expire_time: 3600
  client_id: apisix-dashboard
  client_secret: xxxxxxxxxxxxxxxxxxxxxxxx
  auth_url: https://auth.mycompany.com/realms/mycompany/protocol/openid-connect/auth
  token_url: http://keycloak:8080/realms/mycompany/protocol/openid-connect/token 
  user_info_url: http://keycloak:8080/realms/mycompany/protocol/openid-connect/userinfo  
  redirect_url: https://apisix.mycompany.com/apisix/admin/oidc/callback  
  scope: openid
```

### Expected behavior

1. OIDC login page shows as default
2. keycloak should not error out

### How to Reproduce

```yml
services:
  # APISIX Dashboard
  apisix-dashboard:
    image: apache/apisix-dashboard:latest
    # image: devture/apisix-dashboard:sso-fixes
    restart: always
    volumes:
      - ./apisix_conf/dashboard.yaml:/usr/local/apisix-dashboard/conf/conf.yam
```

with `dashboard.yml` including the change for OIDC.

### Environment

- apisix version (cmd: `apisix version`):
- OS (cmd: `uname -a`):
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `etcd --version`):
- apisix-dashboard version, if have:
- Browser version, if have:
