### ISSUE TITLE
[discuss] use YAML or pretty JSON to store the JSONSchema data

### ISSUE THREAD

**Issue by membphis** [apache/apisix-dashboard#672]
original comment: https://github.com/apache/apisix-dashboard/pull/651/files#r516345355

new way:

1. YAML
2. Pretty JSON

what do you think?

I think we can use YAML or formatted JSON style. The results need to be in order, which makes it easier to compare changes.

```json
{
	"main": {
		"consumer": {
			"type": "object",
			"additionalProperties": false,
			"required": ["username"],
			"properties": {
				"labels": {
					"description": "key/value pairs to specify attributes",
					"maxProperties": 16,
					"type": "object",
					"patternProperties": {
						".*": {
							"description": "value of label",
							"maxLength": 64,
							"type": "string",
							"minLength": 1,
... ...
```

```yaml
main:
  consumer:
    type: object
    additionalProperties: false
    required:
    - username
    properties:
      labels:
        description: key/value pairs to specify attributes
        maxProperties: 16
        type: object
        patternProperties:
          ".*":
            description: value of label
            maxLength: 64
            type: string
            minLength: 1
            pattern: "^[a-zA-Z0-9-_.]+$"
      username:
        type: string
        pattern: "^[a-zA-Z0-9_]+$"
        maxLength: 32
        minLength: 1
      update_time:
        type: integer
... ...
```
