### ISSUE TITLE
can't connect etcd

### ISSUE THREAD

**Issue by backnero** [apache/apisix-dashboard#813]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [*] Bug
- [ ] Requirements
- [ ] Feature or performance improvement
- [ ] Other

___
### Question
- What do you want to know?
```
{"level":"warn","ts":"2020-11-16T08:51:20.064Z","caller":"clientv3/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"endpoint://client-15ecf14a-d558-4821-94e2-9d034dd7a564/gateway-etcd.default.svc.cluster.local:2379","attempt":0,"error":"rpc error: code = Unimplemented desc = Not Found: HTTP status code 404; transport: received the unexpected content-type \"text/plain; charset=utf-8\""}
panic: etcd get failed: rpc error: code = Unimplemented desc = Not Found: HTTP status code 404; transport: received the unexpected content-type "text/plain; charset=utf-8"
goroutine 1 [running]:
main.main()
/usr/local/apisix-dashboard/api/main.go:40 +0x530
```

```
    conf:
      listen:
        host: 0.0.0.0
        port: 8080
      etcd:
        endpoints:
          - gateway-etcd.default.svc.cluster.local:2379
    authentication:
      secret: 
        secret
      expire_time: 3600
      users:
        - username: admin
          password: admin
```
___
### Bug
- Which version of Apache APISIX Dashboard, OS, and Browser?
APISIX 2.0 CENTOS7 DOCKER
DASHBOARD 2.0 CHROME
ETCD 3.4.9
- What happened?
If possible, provide a way to reproduce the error.

___
### Requirements or improvement
- Please describe your requirements or improvement suggestions.
